id: P0ECE60D7
initial_creation_type: input
source_metadata:
  title: Tarkarahasya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Helmut Krasser
  contribution to GRETIL: Helmut Krasser
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:23:31.647642'
last_modified_at: '2022-03-09T15:23:31.647656'
